source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '13.0'


#定义相同的依赖库
def commonPods
#    pod 'LFLiveKit', :path => '.'
  pod 'IQKeyboardManager'
  pod 'SnapKit'
  pod 'SVProgressHUD'
end


target 'RTMPDemo' do
  commonPods
end


